// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using usuarioVideojuego.Context;

#nullable disable

namespace usuarioVideojuego.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231023080727_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("usuarioVideojuego.Models.Email", b =>
                {
                    b.Property<int>("Id_email")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_email"));

                    b.Property<int>("Id_usuario")
                        .HasColumnType("integer");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_email");

                    b.HasIndex("Id_usuario");

                    b.ToTable("Emails");
                });

            modelBuilder.Entity("usuarioVideojuego.Models.Usuario", b =>
                {
                    b.Property<int>("Id_usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_usuario"));

                    b.Property<int>("edad")
                        .HasColumnType("integer");

                    b.Property<string>("genero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombreUsuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_usuario");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("usuarioVideojuego.Models.VideoJuegos", b =>
                {
                    b.Property<int>("Id_videojuego")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_videojuego"));

                    b.Property<bool>("EsGrupal")
                        .HasColumnType("boolean");

                    b.Property<int>("Id_usuario")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombreVideojuego")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("tipoDePago")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_videojuego");

                    b.HasIndex("Id_usuario");

                    b.ToTable("videoJuegos");
                });

            modelBuilder.Entity("usuarioVideojuego.Models.Email", b =>
                {
                    b.HasOne("usuarioVideojuego.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Id_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("usuarioVideojuego.Models.VideoJuegos", b =>
                {
                    b.HasOne("usuarioVideojuego.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Id_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
